### ISSUE TITLE
I cant write password

### ISSUE THREAD

**Issue by kuku233** [evait-security/weeman#2]
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
$ git clone https://github.com/Hypsurus/weeman
Cloning into 'weeman'...
Username for 'https://github.com': kuku233
Password for 'https://kuku233@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Hypsurus/weeman/'

**Comment by Daniilx** [comment]
Тоже не могу

**Comment by dahman006** [comment]
password no righte why plesse help me

**Comment by githubstein** [comment]
I have same probleme

**Comment by Caserol23** [comment]
Yes i had the same there

**Comment by D0Tapk** [comment]
You have to type this command:
git clone https://github.com/evait-security/weeman.git
that error happened because you tried to clone an old repository.
bye
@kuku233 @Daniilx @dahman006 @githubstein @Caserol23

**Comment by evs-pn** [comment]
<img src="https://img.buzzfeed.com/buzzfeed-static/static/2016-07/6/14/campaign_images/buzzfeed-prod-fastlane01/just-a-bunch-of-really-good-spongebob-memes-2-23244-1467828616-0_dblbig.jpg">

**Comment by Entertainment123** [comment]
Send me screenshot
